### ISSUE TITLE
Document required permissions in readme

### ISSUE THREAD

**Issue by jt-nti** [hyperledgendary/fabric-builder-k8s#52]
The following is more than strictly necessary but a good starting point...

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fabric-builder-k8s-role
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - deployments
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
```

Include example `kubectl auth can-i` commands to check for the required permissions.
